### ISSUE TITLE
Error right before it starts commenting

### ISSUE THREAD

**Issue by newbie19999** [p3190131/InstagramCommentsBot#1]
After login, instagram redirects me at target user's profile and not their post. Then the bot crashes. If you could help me, it would be awesome

**Comment by p3190131** [comment]
Hey, first of all I assume you have installed ChromeDriver, right? Secondly, you need to edit the code so that it redirects you to the post you like. In line 8, edit as shown: driver.get('the link of the post you want to spam'). If the script manages to login with the credits succesfully it should be at the post page and start spamming. However, if for some reason it gets to you the main page this can be easily fixed by redirecting it to the post once again after the login. If you don't know how to do that I can do it for you, just let me know.

**Comment by newbie19999** [comment]
Thank you for the fast response, but somehow the problem solved by itself. Everything runs normally now. As you probably imagined, I'm still a newbie programmer, especially in python. Before I close the issue, could you tell me how to create an infinite loop that posts a comment every 20 seconds? Thank you in advance.

**Comment by p3190131** [comment]
I have added 2 more variables in the beginning of the program, check them out. The first one is the comments you want per account (you'll have to subtract it by 1 and you should always have more lines in the names file than the commentsPerAcc). The second one is the waiting time per comment (subtracted by 8). I have already set this one to 12 so the waiting time is now 20 as you needed it, so you'll only have to change the variable of line 4 to your likings. Hope this is not confusing you, it's pretty simple if you read the names of the variables.

**Comment by p3190131** [comment]
I forgot to mention, it now runs infinitely as you wanted.

**Comment by newbie19999** [comment]
Thank you man. Everything is perfect now!
